import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import os
import sys

"""
=============================================================================
TRAINING SCRIPT:
This script trains the Nes2Net backend exclusively. It relies on the pre-extracted
feature vectors (.pt files) generated by `extract_features.py`. 
It does NOT run WavLM or Whisper during training, ensuring fast and efficient 
model updates. 
=============================================================================
"""

# Add parent directory to Path
current_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(current_dir)
sys.path.append(parent_dir)

from models.nes2net import Nes2Net

# --- Configurations ---
DATA_ROOT = os.path.join(parent_dir, "data")
PROCESSED_AUDIO_DIR = os.path.join(DATA_ROOT, "processed") # Where extract_features.py saved the .pt files
RESULTS_DIR = os.path.join(parent_dir, "results")
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

# Training Parameters
BATCH_SIZE = 16 
EPOCHS = 10      # Enough for POC to see the trend
LR = 0.0001      # Gentle learning rate

class PreExtractedFeatureDataset(Dataset):
    def __init__(self, mode, split='train'):
        self.mode = mode
        self.split = split
        self.file_list = []
        self.labels = []
        
        # We assume the data is organized like: data/processed/train/real/file1.pt
        classes = {"real": 0, "fake": 1}
        
        for cls_name, cls_label in classes.items():
            folder_path = os.path.join(PROCESSED_AUDIO_DIR, split, cls_name)
            if os.path.exists(folder_path):
                for fname in os.listdir(folder_path):
                    if fname.endswith('.pt'):
                        self.file_list.append(os.path.join(folder_path, fname))
                        self.labels.append(cls_label)
            else:
                 print(f"Warning: Directory not found - {folder_path}")

    def __len__(self):
        return len(self.file_list)

    def __getitem__(self, idx):
        file_path = self.file_list[idx]
        label = self.labels[idx]
        
        try:
            # Load the dictionary saved by extract_features.py
            data = torch.load(file_path)
            feat = None
            
            if self.mode == 'wavlm':
                # The shape in the dictionary is [Time, 768] (squeezed by extract_features.py)
                feat = data["wavlm"].transpose(0, 1) # Now [768, Time]

            elif self.mode == 'whisper':
                feat = data["whisper"].transpose(0, 1) # Now [768, Time]

            elif self.mode == 'fusion':
                f_w = data["wavlm"].transpose(0, 1)   # [768, T_wavlm]
                f_s = data["whisper"].transpose(0, 1) # [768, T_whisper] (Already aligned by extract_features.py!)
                
                # Concatenate along the channel dimension (dim=0): 768 + 768 = 1536
                feat = torch.cat((f_w, f_s), dim=0) 
            
            # Crop or pad to a fixed length (to allow batching in DataLoader)
            fixed_len = 200 # Reasonable length for Nes2Net (~4 seconds)
            if feat.shape[1] > fixed_len:
                feat = feat[:, :fixed_len]
            elif feat.shape[1] < fixed_len:
                pad_amt = fixed_len - feat.shape[1]
                feat = torch.nn.functional.pad(feat, (0, pad_amt))
                
            return feat, label

        except Exception as e:
            # Fallback in case a file is missing/corrupted
            print(f"Error loading {file_path}: {e}")
            dim = 1536 if self.mode == 'fusion' else 768
            return torch.zeros(dim, 200), label

def train_model(mode_name):
    print(f"\n{'='*40}")
    print(f"🚀 Training Model: {mode_name.upper()}")
    print(f"{'='*40}")
    
    input_dim = 1536 if mode_name == 'fusion' else 768
    model = Nes2Net(input_channels=input_dim).to(DEVICE)
    
    train_ds = PreExtractedFeatureDataset(mode=mode_name, split='train')
    test_ds = PreExtractedFeatureDataset(mode=mode_name, split='test')
    
    if len(train_ds) == 0:
        print(f"No training data found for mode {mode_name}. Please run extract_features.py first.")
        return 0.0

    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, drop_last=True)
    test_loader = DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=False, drop_last=False)
    
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=LR)
    
    best_acc = 0.0
    os.makedirs(RESULTS_DIR, exist_ok=True)
    
    for epoch in range(EPOCHS):
        # Train Mode
        model.train()
        train_loss = 0
        train_correct = 0
        train_total = 0
        
        for feats, labels in train_loader:
            feats, labels = feats.to(DEVICE), labels.to(DEVICE)
            optimizer.zero_grad()
            outputs = model(feats)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()
            
            train_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            train_total += labels.size(0)
            train_correct += (predicted == labels).sum().item()
            
        # Evaluation Mode
        model.eval()
        test_correct = 0
        test_total = 0
        with torch.no_grad():
            for feats, labels in test_loader:
                feats, labels = feats.to(DEVICE), labels.to(DEVICE)
                outputs = model(feats)
                _, predicted = torch.max(outputs.data, 1)
                test_total += labels.size(0)
                test_correct += (predicted == labels).sum().item()
        
        acc = 100 * test_correct / test_total
        print(f"Epoch {epoch+1:02d} | Loss: {train_loss/len(train_loader):.4f} | Train Acc: {100*train_correct/train_total:.1f}% | Test Acc: {acc:.2f}%")
        
        # Save the best model
        if acc > best_acc:
            best_acc = acc
            torch.save(model.state_dict(), os.path.join(RESULTS_DIR, f"best_nes2net_{mode_name}.pth"))
            
    print(f"🏆 Best Result for {mode_name}: {best_acc:.2f}%")
    return best_acc

if __name__ == "__main__":
    results = {}
    
    # Run the ablation study
    results['WavLM'] = train_model('wavlm')
    results['Whisper'] = train_model('whisper')
    results['Fusion'] = train_model('fusion')
    
    print("\n\n📊 --- FINAL RESULTS SUMMARY --- 📊")
    print("-" * 35)
    print(f"{'Model':<15} | {'Accuracy':<10}")
    print("-" * 35)
    for k, v in results.items():
        print(f"{k:<15} | {v:.2f}%")
    print("-" * 35)